PG_COLLECTION_NAME = "pdf_rag"
PG_CONNECTION_STRING = "postgresql://koyeb-adm:zXvOK5VlWQ7S@ep-cool-bar-a12y8xww.ap-southeast-1.pg.koyeb.app/koyebdb"
DATABASE_CONNECTION_STRING = "postgresql://postgres:postgres@localhost:5432/pdf_rag"
EMBEDDING_MODEL = "models/embedding-001"
LLM_MODEL = "gpt-3.5-turbo"
