PG_COLLECTION_NAME = "pdf_rag"
PG_CONNECTION_STRING = "postgresql+psycopg://postgres@localhost:5432/pdf_rag_vectors"
DATABASE_CONNECTION_STRING = "postgresql://postgres:postgres@localhost:5432/pdf_rag"
EMBEDDING_MODEL = "models/embedding-001"
LLM_MODEL = "gpt-3.5-turbo"
